### PR TITLE
Implement Dashboard with Sensor Cards

### LINKED ISSUE #3: Implement the dashboard page
- [ ] Display sensor values (temperature, pressure, humidity) on dashboard

### PR DESCRIPTION
**Pull request by qafui**
Initial implementation of a dashboard with sensor cards for the various data points. Styling is not included in this PR and will be added in a future issue.

### CODE REVIEW

**Comment by naconnors** [comment]
I have a prototype dashboard that I can demo on Thursday.

**Comment by jhodapp** [comment]
Awesome, can't wait to see it!

**Comment by jhodapp** [comment]
@naconnors @qafui Can either of you fill out a more detailed PR description for this work and set an appropriate milestone? I'm happy to review it more thoroughly afterwards.

**Comment by naconnors** [comment]
I converted to draft for now because I spotted an issue when using ambi-rs as the backend instead of the ambi-mock-server. I will push changes to fix it and then move it back to ready for review.

**Review by jhodapp — APPROVED** [review]
Looks great to me, thanks for this Nick/David. This is definitely something we can build upon. Also, thanks for setting up a basic test harness to also build on.

@qafui I think it makes sense for you to review this as well when you get a chance and recommend changes or approve if you're happy.

**Pull request merged**
